version: "3.9"
services:
  mysql:
    container_name: auctionappmysql
    build: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  backend:
    container_name: auctionappbackend
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  webserver:
    container_name: auctionappnginx
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
